spring.profiles.active=prod
app.allowed-origins=https://jonwhitmer.com
spring.application.name=portfolio-backend
server.port=8080

# Python service configuration
# python.service.url=http://localhost:8001

# Contact email destination
contact.email=${MY_EMAIL}

# Email configuration (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.com.jonwhitmer.portfolio=INFO

spring.config.import=optional:file:.env[.properties]