# spring.profiles.active=dev
app.allowed-origins=https://localhost:3000, http://localhost:5173

# application-dev.properties
spring.application.name=portfolio-backend
server.port=8080

# Contact email destination (dev/test)
contact.email=${MY_EMAIL}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=true
logging.level.com.jonwhitmer.portfolio=DEBUG
logging.level.org.springframework.web=DEBUG

app.mail.default-from=noreply@jonwhitmer.dev
spring.config.import=optional:file:.env[.properties]
