services:
  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
        VITE_API_URL: http://localhost:8080
    ports:
      - "5173:80"
    depends_on:
      - portfolio-backend
    environment:
      - VITE_API_URL=http://localhost:8080